export const AUTH_API_ERROR_CODES: Record<string, string> = {
  USER_NOT_FOUND: "Usuário não encontrado.",
  FAILED_TO_CREATE_USER: "Falha ao criar usuário.",
  FAILED_TO_CREATE_SESSION: "Falha ao criar sessão.",
  FAILED_TO_UPDATE_USER: "Falha ao atualizar usuário.",
  FAILED_TO_GET_SESSION: "Falha ao obter a sessão.",
  INVALID_PASSWORD: "Senha inválida.",
  INVALID_EMAIL: "E-mail inválido.",
  INVALID_EMAIL_OR_PASSWORD: "E-mail ou senha inválidos.",
  SOCIAL_ACCOUNT_ALREADY_LINKED: "Conta social já vinculada.",
  PROVIDER_NOT_FOUND: "Provedor não encontrado.",
  INVALID_TOKEN: "Token inválido.",
  ID_TOKEN_NOT_SUPPORTED: "Token de ID não é suportado.",
  FAILED_TO_GET_USER_INFO: "Falha ao obter informações do usuário.",
  USER_EMAIL_NOT_FOUND: "E-mail do usuário não encontrado.",
  EMAIL_NOT_VERIFIED: "E-mail não verificado.",
  PASSWORD_TOO_SHORT: "Senha muito curta.",
  PASSWORD_TOO_LONG: "Senha muito longa.",
  USER_ALREADY_EXISTS: "Usuário já existe.",
  EMAIL_CAN_NOT_BE_UPDATED: "O e-mail não pode ser atualizado.",
  CREDENTIAL_ACCOUNT_NOT_FOUND: "Conta de credenciais não encontrada.",
};
