import "./globals.css";

import type { Metadata } from "next";
import { Poppins } from "next/font/google";

const fontSans = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700"],
  variable: "--font-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className={`${fontSans.variable}`}>{children}</body>
    </html>
  );
}
